name: Essentialslite
version: '${project.version}'
main: be.ilyaan.essentialslite.Essentialslite
api-version: '1.20'
author: Ilyaan
description: 'EssentialsLite is a lightweight essentials plugin for your server.'
commands:
  gmc:
    description: 'I hate gingers'
    usage: '/gmc {player}'
  gms:
    description: 'I hate gingers'
    usage: '/gms {player}'
  gma:
    description: 'I hate gingers'
    usage: '/gma {player}'
  gmsp:
    description: 'I hate gingers'
    usage: '/gmsp {player}'
  repair:
    description: 'I hate gingers'
    usage: '/repair'